from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^accounts/profile/$', 'djauction.views.profile'),
    url(r'^adduser/$', 'djauction.views.add_user'),
    url(r'^addauction/$', 'djauction.views.add_auction'),
    url(r'^auction/(\d+)/addevent/$', 'djauction.views.add_event'),
    url(r'^auction/(\d+)/bids/export/$', 'djauction.views.export_bids'),
    url(r'^auction/(\d+)/checkin/$', 'djauction.views.checkin_user'),
    url(r'^auction/(\d+)/event/(\d+)/$', 'djauction.views.view_event'),
    url(r'^auction/(\d+)/item/bulkadd/$', 'djauction.views.bulk_add_item'),
    url(r'^auction/(\d+)/listevents/$', 'djauction.views.list_events'),
    url(r'^auction/(\d+)/listusers/$', 'djauction.views.list_users'),
    url(r'^auction/(\d+)/listitems/$', 'djauction.views.list_items'),
    url(r'^auction/(\d+)/userpaid/$', 'djauction.views.user_paid_view'),
    url(r'^auction/(\d+)/user/(\d+)/additem/$', 'djauction.views.add_item'),
    url(r'^auction/(\d+)/user/(\d+)/checkout/$', 'djauction.views.checkout_user'),
    url(r'^auction/sendemail/$', 'djauction.views.send_email'),
    url(r'^auction/(\d+)/$', 'djauction.views.view_auction'),
    url(r'^user/(\d+)/auction/(\d+)/$', 'djauction.views.view_user'),
    url(r'^user/bulkadd/$', 'djauction.views.bulk_add_user'),
    url(r'^user/(\d+)/$', 'djauction.views.view_user'),
    url(r'^item/(\d+)/$', 'djauction.views.view_item'),
    url(r'^$', 'djauction.views.index'),
)
